### ISSUE TITLE
HTML body in email

### ISSUE THREAD

**Issue by nickyadvokaat** [jhawkinsatgood/gdcontributor#1]
In `GdcServiceRequestSendEmail.h` is it somehow possible to set HTML as body data? I'd like to include a link in the mail body.

**Comment by jhawkinsatgood** [comment]
I have heard that if the body starts with `<html>` then BlackBerry Work treats the rest as HTML format.

**Comment by nickyadvokaat** [comment]
I used `setBody:(NSString *)body` to set an HTML string, but it doesn't seem to be working:
![1](https://user-images.githubusercontent.com/1654962/27376987-ff0a4ba2-5673-11e7-8853-bd1c482eb1d9.jpg)

**Comment by jhawkinsatgood** [comment]
Sorry about that. It seems I heard wrong. Have you tried asking on the BlackBerry Dynamics application developer portal forum? It's here:
https://community.blackberry.com/community/gdn/resources/developer_community

**Comment by nickyadvokaat** [comment]
Looks like it is not possible([*](https://community.blackberry.com/message/206308#206308)), although the results on the forum are quite old. Any chance this feature will be added to GDContributor in the future? Otherwise consider this issue closed.

**Comment by jhawkinsatgood** [comment]
Sorry, that thread is for BlackBerry 10 and BBOS devices. You might have to ask a new question, and make it specific to BlackBerry Dynamics and the Send Email service.
